# Generated by Django 4.1.7 on 2023-02-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariotipro', '0002_departamento_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventariotipro.monitores'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='periferico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventariotipro.perifericos'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventariotipro.equipos'),
        ),
    ]
