# Generated by Django 4.1.7 on 2023-02-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariotipro', '0003_asignacion_monitor_asignacion_periferico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitores',
            name='serieproducto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
