# Generated by Django 4.2.2 on 2023-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariotipro', '0005_alter_equipos_serieproducto_alter_equipos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(choices=[['Informatica', 'Informatica'], ['Corporativo', 'Corporativo'], ['Ventas', 'Ventas'], ['BTA', 'BTA'], ['Grupos', 'Grupos'], ['BTO', 'BTO'], ['Administracion', 'Administracion'], ['Operaciones', 'Operaciones'], ['Gerencia General', 'Gerencia General'], ['KAM', 'KAM'], ['Despacho', 'Despacho']], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='estado',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], default='Inactivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='hostname',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='serieproducto',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='tipo',
            field=models.CharField(blank=True, choices=[['DESKTOP', 'DESKTOP'], ['LAPTOP', 'LAPTOP']], default='DESKTOP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='estado',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], default='Inactivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='serieproducto',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='perifericos',
            name='estado',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], default='Inactivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='perifericos',
            name='serieproducto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
